apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: wi8cabk57-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/rhtap-qe:883d999e136fc33019741860e06d564b218b47b3@sha256:4aaa3232db1f56efa0032d6fb19d55592942f174cedaf0b7c8cfd026c1690900
        name: container-image  
